name: myenv
dependencies:
  - python=3.8
  - matplotlib
  - pandas
  - numpy
  - pip
  - pip:
      - torchvision
      - pytorch-lightning
      - lightning-bolts
      - tensorboard
      - scikit-learn
